#ifndef HEATER_CONFIG_H
#define HEATER_CONFIG_H

#define HEATER_WORK_START_ADDR 0

#define HEATER_UNIT_SYSTEM_TIME_BASE 0
#define HEATER_UNIT_SYSTEM_TIME_LENGTH 5

#define HEATER_MODBUS_OFFSET_ADDR 50

#define HEATER_WORK_SWITCH_ADDR (200 + 26)

#define HEATER_TEMPERATURE_SENSOR_BASE 41
#define HEATER_TEMPERATURE_SENSOR_LENGTH 7

#define HEATER_UNIT_AVERAGE_TEMP_ADDR 49


#define HEATER_REAL_TIME_DATA_BASE 10
#define HEATER_REAL_TIME_DATA_LENGTH 9

#define HEATER_PARAMETER_SETTINGS_BASE (200 + 30)
#define HEATER_PARAMETER_SETTINGS_LENGTH 20

#define HEATER_REMOTE_OPERATION_BASE 9
#define HEATER_REMOTE_OPERATION_LENGTH 2

#define HEATER_FAULT_STATUS_BASE 51
#define HEATER_FAULT_STATUS_LENGTH 5

#define HEATER_RECORD_TIME_BASE 100
#define HEATER_RECORD_TIME_LENGTH 5

#define HEATER_RECORD_TIME_VALID_TAG_ADDR 105

#define HEATER_HISTORY_RECORD_BASE 118
#define HEATER_HISTORY_RECORD_ITEM_LENGTH 8

#define HEATER_WORK_OR_FAULT_HISTORY_RECORD_TIEM_NUM 20
#define HEATER_WORK_OR_FAULT_HISTORY_RECORD_TIEM_LENGTH 6

#define HEATER_WORK_RECORD_BASE 600
#define HEATER_WORK_RECORD_LENGTH 120
#define HEATER_FAULT_RECORD_BASE 800
#define HEATER_FAULT_RECORD_LENGTH 120

#define HEATER_CONTROL_REGISTER_BASE (200 + 25)
#define HEATER_PARAMETER_SETTINGS_RESET_OFFSET (13 + 1)
#define HEATER_FAULT_RECORD_CLEAR_OFFSET (9 + 1)
#define HEATER_WORK_RECORD_CLEAR_OFFSET (10 + 1)

#define MODBUS_TCP_PORT 502
#define MODBUS_SLAVE_ADDR 6

#define FAN_TOWER_GROUP 2
#define HEATER_QUANITY_NUM 5

#endif
