#ifndef HEATER_MODBUS_OFFSET_ADDRESS_H
#define HEATER_MODBUS_OFFSET_ADDRESS_H

#define HEATER_WORK_START_ADDR 0

#define HEATER_UNIT_SYSTEM_TIME_BASE 0
#define HEATER_UNIT_SYSTEM_TIME_LENGTH 5

#define HEATER_TEMPERATURE_SENSOR_BASE 41
#define HEATER_TEMPERATURE_SENSOR_LENGTH 7

#define HEATER_UNIT_AVERAGE_TEMP_ADDR 49

#define MODBUS_OFFSET_ADDR 50


#define HEATER_REAL_TIME_DATA_BASE 10
#define HEATER_REAL_TIME_DATA_LENGTH 9

#define HEATER_PARAMETER_SETTINGS_BASE (200 + 30)
#define HEATER_PARAMETER_SETTINGS_LENGTH 20

#define HEATER_REMOTE_OPERATION_BASE 9
#define HEATER_REMOTE_OPERATION_LENGTH 2

#define HEATER_FAULT_STATUS_ADDR (200 + 5)


#define HEATER_HISTORY_RECORD_TIME_ITEM 5
#define HEATER_HISTORY_RECORD_BASE 110
#define HEATER_HISTORY_RECORD_ITEM_LENGTH 8

#define HEATER_WORK_RECORD_BASE 600
#define HEATER_WORK_RECORD_LENGTH 120
#define HEATER_FAULT_RECORD_BASE 800
#define HEATER_FAULT_RECORD_LENGTH 120


#endif
