#ifndef HEATER_MODBUS_OFFSET_ADDRESS_H
#define HEATER_MODBUS_OFFSET_ADDRESS_H

#define HEATER_WORK_START_ADDR 0

#define HEATER_UNIT_SYSTEM_TIME_BASE 0
#define HEATER_UNIT_SYSTEM_TIME_LENGTH 5

#define HEATER_TEMPERATURE_SENSOR_BASE 41
#define HEATER_TEMPERATURE_SENSOR_LENGTH 7

#define HEATER_UNIT_AVERAGE_TEMP_ADDR 49

#define MODBUS_OFFSET_ADDR 50

#define HEATER_FAULT_STATUS_ADDR 5

#define HEATER_REAL_TIME_DATA_BASE 10
#define HEATER_REAL_TIME_DATA_LENGTH 9

#define HEATER_PARAMETER_SETTINGS_BASE 30
#define HEATER_PARAMETER_SETTINGS_LENGTH 20

#define HEATER_REMOTE_OPERATION_BASE 9
#define HEATER_REMOTE_OPERATION_LENGTH 2

#endif
